//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zoo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Animal.
    /// </summary>
    //  *** Start programmer edit section *** (Animal CustomAttributes)

    //  *** End programmer edit section *** (Animal CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AnimalE", new string[] {
            "Name as \'Name\'",
            "AnimalType as \'Animal type\'",
            "AnimalType.Name as \'Name\'"}, Hidden=new string[] {
            "AnimalType.Name"})]
    [AssociatedDetailViewAttribute("AnimalE", "Homes", "AnimalHomeE", true, "", "Homes", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("AnimalE", "AnimalType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("AnimalL", new string[] {
            "Name as \'Name\'",
            "AnimalType.Name as \'Name\'"})]
    public class Animal : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Zoo.AnimalType fAnimalType;
        
        private IIS.Zoo.DetailArrayOfAnimalHome fHomes;
        
        //  *** Start programmer edit section *** (Animal CustomMembers)

        //  *** End programmer edit section *** (Animal CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Animal.Name CustomAttributes)

        //  *** End programmer edit section *** (Animal.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Animal.Name Get start)

                //  *** End programmer edit section *** (Animal.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Animal.Name Get end)

                //  *** End programmer edit section *** (Animal.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Animal.Name Set start)

                //  *** End programmer edit section *** (Animal.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Animal.Name Set end)

                //  *** End programmer edit section *** (Animal.Name Set end)
            }
        }
        
        /// <summary>
        /// Animal.
        /// </summary>
        //  *** Start programmer edit section *** (Animal.AnimalType CustomAttributes)

        //  *** End programmer edit section *** (Animal.AnimalType CustomAttributes)
        public virtual IIS.Zoo.AnimalType AnimalType
        {
            get
            {
                //  *** Start programmer edit section *** (Animal.AnimalType Get start)

                //  *** End programmer edit section *** (Animal.AnimalType Get start)
                IIS.Zoo.AnimalType result = this.fAnimalType;
                //  *** Start programmer edit section *** (Animal.AnimalType Get end)

                //  *** End programmer edit section *** (Animal.AnimalType Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Animal.AnimalType Set start)

                //  *** End programmer edit section *** (Animal.AnimalType Set start)
                this.fAnimalType = value;
                //  *** Start programmer edit section *** (Animal.AnimalType Set end)

                //  *** End programmer edit section *** (Animal.AnimalType Set end)
            }
        }
        
        /// <summary>
        /// Animal.
        /// </summary>
        //  *** Start programmer edit section *** (Animal.Homes CustomAttributes)

        //  *** End programmer edit section *** (Animal.Homes CustomAttributes)
        public virtual IIS.Zoo.DetailArrayOfAnimalHome Homes
        {
            get
            {
                //  *** Start programmer edit section *** (Animal.Homes Get start)

                //  *** End programmer edit section *** (Animal.Homes Get start)
                if ((this.fHomes == null))
                {
                    this.fHomes = new IIS.Zoo.DetailArrayOfAnimalHome(this);
                }
                IIS.Zoo.DetailArrayOfAnimalHome result = this.fHomes;
                //  *** Start programmer edit section *** (Animal.Homes Get end)

                //  *** End programmer edit section *** (Animal.Homes Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Animal.Homes Set start)

                //  *** End programmer edit section *** (Animal.Homes Set start)
                this.fHomes = value;
                //  *** Start programmer edit section *** (Animal.Homes Set end)

                //  *** End programmer edit section *** (Animal.Homes Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AnimalE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalE", typeof(IIS.Zoo.Animal));
                }
            }
            
            /// <summary>
            /// "AnimalL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalL", typeof(IIS.Zoo.Animal));
                }
            }
        }
    }
}
