//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zoo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Animal type.
    /// </summary>
    //  *** Start programmer edit section *** (AnimalType CustomAttributes)

    //  *** End programmer edit section *** (AnimalType CustomAttributes)
    [AutoAltered()]
    [Caption("Animal type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AnimalTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("AnimalTypeL", new string[] {
            "Name as \'Name\'"})]
    public class AnimalType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (AnimalType CustomMembers)

        //  *** End programmer edit section *** (AnimalType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (AnimalType.Name CustomAttributes)

        //  *** End programmer edit section *** (AnimalType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (AnimalType.Name Get start)

                //  *** End programmer edit section *** (AnimalType.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (AnimalType.Name Get end)

                //  *** End programmer edit section *** (AnimalType.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (AnimalType.Name Set start)

                //  *** End programmer edit section *** (AnimalType.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (AnimalType.Name Set end)

                //  *** End programmer edit section *** (AnimalType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AnimalTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalTypeE", typeof(IIS.Zoo.AnimalType));
                }
            }
            
            /// <summary>
            /// "AnimalTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalTypeL", typeof(IIS.Zoo.AnimalType));
                }
            }
        }
    }
}
