//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zoo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Animal home.
    /// </summary>
    //  *** Start programmer edit section *** (AnimalHome CustomAttributes)

    //  *** End programmer edit section *** (AnimalHome CustomAttributes)
    [AutoAltered()]
    [Caption("Animal home")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AnimalHomeE", new string[] {
            "Location as \'Location\'"})]
    public class AnimalHome : ICSSoft.STORMNET.DataObject
    {
        
        private string fLocation;
        
        private IIS.Zoo.Animal fAnimal;
        
        //  *** Start programmer edit section *** (AnimalHome CustomMembers)

        //  *** End programmer edit section *** (AnimalHome CustomMembers)

        
        /// <summary>
        /// Location.
        /// </summary>
        //  *** Start programmer edit section *** (AnimalHome.Location CustomAttributes)

        //  *** End programmer edit section *** (AnimalHome.Location CustomAttributes)
        [StrLen(255)]
        public virtual string Location
        {
            get
            {
                //  *** Start programmer edit section *** (AnimalHome.Location Get start)

                //  *** End programmer edit section *** (AnimalHome.Location Get start)
                string result = this.fLocation;
                //  *** Start programmer edit section *** (AnimalHome.Location Get end)

                //  *** End programmer edit section *** (AnimalHome.Location Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (AnimalHome.Location Set start)

                //  *** End programmer edit section *** (AnimalHome.Location Set start)
                this.fLocation = value;
                //  *** Start programmer edit section *** (AnimalHome.Location Set end)

                //  *** End programmer edit section *** (AnimalHome.Location Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Zoo.Animal.
        /// </summary>
        //  *** Start programmer edit section *** (AnimalHome.Animal CustomAttributes)

        //  *** End programmer edit section *** (AnimalHome.Animal CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Zoo.Animal Animal
        {
            get
            {
                //  *** Start programmer edit section *** (AnimalHome.Animal Get start)

                //  *** End programmer edit section *** (AnimalHome.Animal Get start)
                IIS.Zoo.Animal result = this.fAnimal;
                //  *** Start programmer edit section *** (AnimalHome.Animal Get end)

                //  *** End programmer edit section *** (AnimalHome.Animal Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (AnimalHome.Animal Set start)

                //  *** End programmer edit section *** (AnimalHome.Animal Set start)
                this.fAnimal = value;
                //  *** Start programmer edit section *** (AnimalHome.Animal Set end)

                //  *** End programmer edit section *** (AnimalHome.Animal Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AnimalHomeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalHomeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalHomeE", typeof(IIS.Zoo.AnimalHome));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of AnimalHome.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfAnimalHome CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfAnimalHome CustomAttributes)
    public class DetailArrayOfAnimalHome : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Zoo.DetailArrayOfAnimalHome members)

        //  *** End programmer edit section *** (IIS.Zoo.DetailArrayOfAnimalHome members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type AnimalHome by index.
        /// </summary>
        /// <summary>
        /// Adds object with type AnimalHome.
        /// </summary>
        public DetailArrayOfAnimalHome(IIS.Zoo.Animal fAnimal) : 
                base(typeof(AnimalHome), ((ICSSoft.STORMNET.DataObject)(fAnimal)))
        {
        }
        
        public IIS.Zoo.AnimalHome this[int index]
        {
            get
            {
                return ((IIS.Zoo.AnimalHome)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Zoo.AnimalHome dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
